default_stages: [pre-commit]
fail_fast: true
default_language_version:
  golang: system

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: detect-private-key
  - repo: https://github.com/google/yamlfmt
    rev: v0.17.2
    hooks:
      - id: yamlfmt
  - repo: https://github.com/adhtruong/mirrors-typos
    rev: v1.37.0
    hooks:
      - id: typos
