version: '3'

tasks:
  default:
    silent: true
    cmds:
      - task --list

  go:fmt:
    desc: format all go code
    cmds:
      - go fmt ./...

  go:lint:
    desc: runs golangci-lint, the most annoying opinionated linter ever
    cmds:
      - golangci-lint run --config=.golangci.yaml --verbose --fix

  go:test:
    desc: runs and outputs results of created go tests
    cmds:
      - go test -v ./...

  go:tidy:
    desc: runs go mod tidy on the backend
    aliases: [tidy]
    cmds:
      - go mod tidy

  go:all:
    aliases: [go]
    desc: runs all go test and lint related tasks
    cmds:
      - task: go:tidy
      - task: go:fmt
      - task: go:lint
      - task: go:test

  precommit-full:
    desc: Lint the project against all files
    cmds:
      - pre-commit install && pre-commit install-hooks
      - pre-commit autoupdate
      - pre-commit run --show-diff-on-failure --color=always --all-files

  init:
    desc: Initialize the repository with the actual repo name
    vars:
      REPO_NAME:
        sh: git remote get-url origin | sed 's/.*\///;s/\.git$//'
    cmds:
      - echo "Initializing repository as {{.REPO_NAME}}"
      - find . -type f \( -name "*.md" -o -name "*.properties" -o -name "*.yaml" -o -name "*.yml" \) -not -name "Taskfile.yaml" | xargs -I {} sed -i '' 's/REPONAME/{{.REPO_NAME}}/g' {}
      - go mod init github.com/theopenlane/{{.REPO_NAME}}
      - task: precommit-full
      - rm INIT.md
      - echo "Repository initialized as github.com/theopenlane/{{.REPO_NAME}}"
